### ISSUE TITLE
Error: Failed to decode image

### ISSUE THREAD

**Issue by Lcccocoa** [yyued/SVGAPlayer-Flutter#68]
E/FlutterJNI(11939): Failed to decode image
E/FlutterJNI(11939): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(11939): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(11939): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:169)
E/FlutterJNI(11939): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:247)
E/FlutterJNI(11939): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1753)
E/FlutterJNI(11939): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1746)
E/FlutterJNI(11939): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:431)
I/flutter (11939): ┌
I/flutter (11939): │ ⛔ #0      _futurize (dart:ui/painting.dart:5394:5)
I/flutter (11939): │ ⛔ #1      ImageDescriptor.encoded (dart:ui/painting.dart:5262:12)
I/flutter (11939): │ ⛔ #2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ #3      decodeImageFromList (package:flutter/src/painting/image_decoder.dart:24:26)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ #4      SVGAParser._decodeImageItem (package:svgaplayer_flutter/parser.dart:95:21)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ #5      SVGAParser._prepareResources.<anonymous closure> (package:svgaplayer_flutter/parser.dart:78:27)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ #6      Future.wait.<anonymous closure> (dart:async/future.dart)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ #7      AnimalController._process (package:baselib/widget/animal/svga_animal_controller.dart:79:31)
I/flutter (11939): │ ⛔ <asynchronous suspension>
I/flutter (11939): │ ⛔ 
I/flutter (11939): └

**Comment by PonyCui** [comment]
Please provide more information.

**Comment by abdalazeez1** [comment]
have same error when  try get image from gallery in A50 Android 11

**Comment by Slihao** [comment]
E/FlutterJNI(23245): Failed to decode image
E/FlutterJNI(23245): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'invalid input'Input contained an error.
E/FlutterJNI(23245): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(23245): 	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI(23245): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI(23245): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1863)
E/FlutterJNI(23245): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1856)
E/FlutterJNI(23245): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:448)


目前在 三星、小米的一些机型上会使应用崩溃
